
spring:
  application:
    name: chatroom
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  mvc:
    static-path-pattern: /**  #加载静态资源路径配置
server:
  port: 9999


